name: Tag Bump
permissions:
  contents: write

run-name: ${{ github.actor }} triggers tag version bump

on:
  push:
    branches:
      - main

jobs:
  bump-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          fetch-depth: 0  
          node-version: '22'
      - run: npm install
      - run: node ./.git-tag/tag-bump.js
