name: Tag Bump

permissions:
  contents: write

on:
  push:
    branches:
      - main
  workflow_run:
    workflows: ["Unit Tests", "Build"]
    types:
      - completed

jobs:
  bump-version:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v4
        with:
          node-version: '22'
      - run: git fetch --tags
      - run: npm install
      - run: node ./.git-tag/tag-bump.js
